export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const SET_INGRIDIENT = "SET_INGRIDIENT";
export const FETCH_INGRIDIENTS_FAILED = "FETCH_INGRIDIENTS_FAILED";

export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";
export const PURCHASE_START = "PURCHASE_START";
