export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const SET_INGRIDIENT = "SET_INGRIDIENT";
export const FETCH_INGRIDIENTS_FAILED = "FETCH_INGRIDIENTS_FAILED";

export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";
export const PURCHASE_START = "PURCHASE_START";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

